### ISSUE TITLE
How is isMobile populated

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/app-layout-templates#3]
I see at https://github.com/PolymerElements/app-layout-templates/blob/master/nav-list-detail/src/x-app.html#L38 there is a function call [[_computeListWidth(_isMobile)]] ; how does it know the value of isMobile, who populates it? I don't see any media-query hence am confused.

**Comment by askibinski** [comment]
I'm wondering myself... The other list-card-over example (https://github.com/PolymerElements/app-layout-templates/blob/master/list-card-over/src/x-app.html) does have a media query element which binds the value of _isMobile:

<iron-media-query query="(max-width: 780px)" query-matches="{{_isMobile}}"></iron-media-query>

But I'm not sure how this works in nav-list-detail because I don't see such a query. Weird.

**Comment by frankiefu** [comment]
`paper-drawer-panel` has a `narrow` property and `_isMobile` is bind to that to know when the drawer is in narrow layout.

**Comment by devAtPolydeals** [comment]
@frankiefu so based on responsive-width="600px" it makes narrow = true and that inturn makes isMobile = true correct?

**Comment by frankiefu** [comment]
@devAtPolydeals yes, that's correct.

**Comment by devAtPolydeals** [comment]
cool thanks @frankiefu  :+1:
